### ISSUE TITLE
TODO v4 Roxanne

### ISSUE THREAD

**Issue by txj-xyz** [txj-xyz/roxanne-music-bot#106]
- [ ] Implement proper `DefinitelyTyped` `.d.ts` files for all `class` types inside `./src/types/**.d.ts`
- [ ] Add all `Shoukaku` inside dynamic Module
- [ ] Add support for extending Dynamic Modules
- [ ] Fix `UtilityHandler` to a `declare global BotUtility { }` module
- [ ] Add generics to the bot? Probably don't need this
- [ ] Add support for modules that add `Cluster` features
- [ ] Fix music code from `ES6 -> ESNext` to bring up to date
