### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by txj-xyz** [txj-xyz/roxanne-music-bot#64]
- [x] Fix `voiceStateUpdate` improperly tracking voice states when bot is either manually moved with nobody in the channel or with `/move`
- [x] Fix Youtube Shorts url replace `/shorts/` with `/watch?v=` when requesting.
- [x] Add integration for `voiceStateUpdate` and leaving when a channel is empty and nobody is left.
